# .github/workflows/ci-cd.yml

name: CI/CD Pipeline for Node.js App

# Triggers the workflow on a push event to the main branch [cite: 26]
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code from the repository [cite: 16]
    - name: Check out code
      uses: actions/checkout@v3

    # 2. Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3. Install dependencies
    - name: Install Dependencies
      run: npm install

    # 4. Run tests 
    - name: Run Tests
      run: npm test

    # 5. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 6. Build and push Docker image to Docker Hub 
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest # Change 'my-node-app' if you like

  # --- OPTIONAL DEPLOYMENT JOB ---
  # This job automatically deploys the app to a server.
  # It only runs if the 'build-and-push' job succeeds.
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push  # Depends on the previous job

    steps:
    - [cite_start]name: Deploy to Remote Server [cite: 19]
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # 1. Pull the new image from Docker Hub
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest

          # 2. Stop and remove the old container, ignoring errors if it doesn't exist
          docker stop my-node-app || true
          docker rm my-node-app || true

          # 3. Run the new container
          docker run -d -p 3000:3000 --name my-node-app ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest